insert into performer (id, surname, name, fathername, instrumentid)
values
	(null,"Abbado", "Marchello", null, 1),
	(null,"Ab", "Lev", "Efimovich", 1),
	(null,"Andreoli", "Karlo",  null, 1),
	(null,"Agostini", "Paolo", null, 2),
	(null,"Ayvin", "Alnes", null, 2),
	(null,"Abel", "Christian", "Ferdinand", 3),
	(null,"Bahur", "Simon", null, 3),
	(null,"Bagelman", "David", null, 3),
	(null,"Rostopovich", "Mstislav", "Leopoldovich", 4),
	(null,"Kazals", "Pablo", null, 4),
	(null,"Du Pre", "Zhaklin", null, 4),
	(null,"Hendrix", "Jimmy", null, 5),
	(null,"Allman", "Dwaynt", "The Rock", 5),
	(null,"King", "Bb", null, 5),
	(null,"Jonson", "Robert", null, 5),
	(null,"Agofonov", "Nikita", "Viktorovich", 6),
	(null,"Allen", "Heywood", null, 6),
	(null,"Blazhevich", "Vladislav", "Michaylovich", 7),
	(null,"Dosadin", "Vladimir", "Nikolaevich", 7),
	(null,"Biden", "Joe", null, 8),
	(null,"Trump", "Donald", null, 8),
	(null,"Barker", "Travis", null, 9);